#!/usr/bin/env python3
"""Finite-field invariant miner for generalized Fermat signatures.

For F(A,B,C)=A^x+B^y-C^z, search for low-degree polynomials P(A,B,C)
over F_p vanishing on every primitive solution, then remove the obvious
subspace generated by polynomial multiples of F.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

Monomial = Tuple[int, int, int]
Vector = List[int]


@dataclass
class PrimeReport:
    p: int
    primitive_solution_count: int
    monomial_count: int
    vanishing_space_dimension: int
    obvious_ideal_dimension: int
    extra_dimension: int
    extra_relations: List[Dict[str, object]]


def monomials_upto_degree(d: int) -> List[Monomial]:
    mons = []
    for total in range(d + 1):
        for i in range(total + 1):
            for j in range(total - i + 1):
                mons.append((i, j, total - i - j))
    return mons


def primitive_solutions(x: int, y: int, z: int, p: int) -> List[Tuple[int, int, int]]:
    sols = []
    for a in range(p):
        ax = pow(a, x, p)
        for b in range(p):
            rhs = (ax + pow(b, y, p)) % p
            for c in range(p):
                if pow(c, z, p) == rhs and (a, b, c) != (0, 0, 0):
                    sols.append((a, b, c))
    return sols


def rref_mod(matrix: List[Vector], p: int) -> Tuple[List[Vector], List[int]]:
    if not matrix:
        return [], []
    a = [row[:] for row in matrix]
    m, n = len(a), len(a[0])
    pivots = []
    r = 0
    for c in range(n):
        pivot = next((i for i in range(r, m) if a[i][c] % p), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        inv = pow(a[r][c] % p, -1, p)
        a[r] = [(v * inv) % p for v in a[r]]
        for i in range(m):
            if i == r:
                continue
            factor = a[i][c] % p
            if factor:
                a[i] = [(a[i][j] - factor * a[r][j]) % p for j in range(n)]
        pivots.append(c)
        r += 1
        if r == m:
            break
    return a, pivots


def nullspace_mod(matrix: List[Vector], p: int) -> List[Vector]:
    if not matrix:
        return []
    rref, pivots = rref_mod(matrix, p)
    n = len(matrix[0])
    free = [j for j in range(n) if j not in pivots]
    basis = []
    for f in free:
        v = [0] * n
        v[f] = 1
        for row_idx, pc in enumerate(pivots):
            v[pc] = (-rref[row_idx][f]) % p
        basis.append(v)
    return basis


def rank_mod(vectors: List[Vector], p: int) -> int:
    return len(rref_mod(vectors, p)[1]) if vectors else 0


def eval_row(point: Tuple[int, int, int], mons: Sequence[Monomial], p: int) -> Vector:
    a, b, c = point
    pa = [1]
    pb = [1]
    pc = [1]
    for _ in range(max(i for i, _, _ in mons)): pa.append(pa[-1] * a % p)
    for _ in range(max(j for _, j, _ in mons)): pb.append(pb[-1] * b % p)
    for _ in range(max(k for _, _, k in mons)): pc.append(pc[-1] * c % p)
    return [(pa[i] * pb[j] * pc[k]) % p for i, j, k in mons]


def obvious_multiples(x: int, y: int, z: int, degree: int,
                       mons: Sequence[Monomial], p: int) -> List[Vector]:
    index = {m: i for i, m in enumerate(mons)}
    max_f_degree = max(x, y, z)
    if degree < max_f_degree:
        return []
    vectors = []
    for u, v, w in monomials_upto_degree(degree - max_f_degree):
        vec = [0] * len(mons)
        terms = [((u + x, v, w), 1), ((u, v + y, w), 1), ((u, v, w + z), -1)]
        if all(mon in index for mon, _ in terms):
            for mon, coeff in terms:
                vec[index[mon]] = (vec[index[mon]] + coeff) % p
            vectors.append(vec)
    return vectors


def canonical_support(vec: Vector, mons: Sequence[Monomial], p: int):
    nz = [(mons[i], c % p) for i, c in enumerate(vec) if c % p]
    if not nz:
        return tuple()
    inv = pow(nz[0][1], -1, p)
    return tuple((m, c * inv % p) for m, c in nz)


def polynomial_string(support, p: int) -> str:
    parts = []
    for (i, j, k), coeff in support:
        signed = coeff if coeff <= p // 2 else coeff - p
        factors = []
        if i: factors.append("A" if i == 1 else f"A^{i}")
        if j: factors.append("B" if j == 1 else f"B^{j}")
        if k: factors.append("C" if k == 1 else f"C^{k}")
        parts.append(f"{signed:+d}*{'*'.join(factors) if factors else '1'}")
    return " ".join(parts).lstrip("+")


def complement_basis(vanish_basis: List[Vector], obvious: List[Vector], p: int) -> List[Vector]:
    current = obvious[:]
    current_rank = rank_mod(current, p)
    extras = []
    for v in vanish_basis:
        new_rank = rank_mod(current + [v], p)
        if new_rank > current_rank:
            extras.append(v)
            current.append(v)
            current_rank = new_rank
    return extras


def analyze_prime(x: int, y: int, z: int, p: int, degree: int,
                  max_relations: int) -> PrimeReport:
    mons = monomials_upto_degree(degree)
    sols = primitive_solutions(x, y, z, p)
    vanish = nullspace_mod([eval_row(s, mons, p) for s in sols], p)
    obvious = obvious_multiples(x, y, z, degree, mons, p)
    extras = complement_basis(vanish, obvious, p)
    relations = []
    for vec in extras[:max_relations]:
        support = canonical_support(vec, mons, p)
        relations.append({
            "support": [{"exponents": list(mon), "coefficient_mod_p": coeff} for mon, coeff in support],
            "polynomial": polynomial_string(support, p),
            "term_count": len(support),
        })
    return PrimeReport(p, len(sols), len(mons), len(vanish), rank_mod(obvious, p), len(extras), relations)


def primes_up_to(n: int) -> List[int]:
    sieve = [True] * (n + 1)
    if n >= 0: sieve[0] = False
    if n >= 1: sieve[1] = False
    for q in range(2, int(n ** 0.5) + 1):
        if sieve[q]:
            for k in range(q * q, n + 1, q): sieve[k] = False
    return [i for i, v in enumerate(sieve) if v]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--signature", nargs=3, type=int, required=True)
    ap.add_argument("--degree", type=int, default=7)
    ap.add_argument("--prime-bound", type=int, default=19)
    ap.add_argument("--max-relations", type=int, default=8)
    ap.add_argument("--output", default="-")
    ns = ap.parse_args()
    x, y, z = ns.signature
    reports = [asdict(analyze_prime(x, y, z, p, ns.degree, ns.max_relations))
               for p in primes_up_to(ns.prime_bound) if p != 2]
    support_frequency: Dict[str, int] = {}
    support_examples: Dict[str, object] = {}
    for report in reports:
        seen = set()
        for relation in report["extra_relations"]:
            key = json.dumps([term["exponents"] for term in relation["support"]])
            if key not in seen:
                support_frequency[key] = support_frequency.get(key, 0) + 1
                support_examples[key] = relation
                seen.add(key)
    persistent = []
    for key, count in sorted(support_frequency.items(), key=lambda item: (-item[1], item[0])):
        if count >= 2:
            persistent.append({"prime_count": count, "support": json.loads(key), "example": support_examples[key]})
    output = {
        "signature": [x, y, z],
        "degree": ns.degree,
        "reports": reports,
        "persistent_support_candidates": persistent,
        "interpretation": (
            "An extra relation at one prime is normally a finite-field artifact. "
            "Only sparse support patterns recurring across several primes deserve "
            "symbolic investigation over the integers."
        ),
    }
    text = json.dumps(output, indent=2)
    if ns.output == "-":
        print(text)
    else:
        Path(ns.output).write_text(text + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()