#!/usr/bin/env python3
"""Certify the divided-Frobenius rank on the genus-2 quotient at infinity.

For an even-degree sextic PARI returns a 5-dimensional Monsky--Washnitzer
space.  The extra Frobenius line has eigenvalue -7.  Modulo 49, for residue
class v=1,...,6 it is generated by

    e_3 + 7*v*e_5

in PARI's ordered basis.  Modulo 7 this is the third basis vector, lying in the
raw quotient by the first two holomorphic forms.  The divided lower-left block
has zero component along that extra line, so its rank survives unchanged on
the 4-dimensional genus-2 quotient.
"""

from __future__ import annotations

P = 7
P2 = 49

MATRICES = {
    1: [[35,35,0,25,14],[0,42,7,0,20],[0,0,42,0,0],[28,0,0,14,21],[0,21,0,0,7]],
    2: [[21,21,0,32,28],[0,21,28,0,33],[0,0,42,0,0],[14,0,0,28,35],[0,21,0,0,28]],
    3: [[42,42,0,3,42],[0,35,14,0,4],[0,0,42,0,0],[42,0,0,7,42],[0,28,0,0,14]],
    4: [[42,42,0,39,7],[0,35,14,0,3],[0,0,42,0,0],[7,0,0,7,42],[0,21,0,0,14]],
    5: [[21,21,0,3,21],[0,21,28,0,23],[0,0,42,0,0],[35,0,0,28,35],[0,28,0,0,28]],
    6: [[35,35,0,45,35],[0,42,7,0,36],[0,0,42,0,0],[21,0,0,14,21],[0,28,0,0,7]],
}


def matvec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(a*b for a, b in zip(row, vector)) % P2 for row in matrix]


def rank2(matrix: list[list[int]]) -> int:
    det = (matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]) % P
    if det:
        return 2
    return 1 if any(x % P for row in matrix for x in row) else 0


def main() -> None:
    print("v extra_generator quotient_divided_block rank")
    for v, matrix in MATRICES.items():
        extra = [0, 0, 1, 0, 7*v]
        shifted = [row[:] for row in matrix]
        for i in range(5):
            shifted[i][i] += 7
        if matvec(shifted, extra) != [0]*5:
            raise AssertionError(f"v={v}: claimed -7 eigenvector fails mod 49")

        raw = [[matrix[i][j] for j in range(2)] for i in range(2, 5)]
        if any(x % P for row in raw for x in row):
            raise AssertionError(f"v={v}: lower-left block not divisible by 7")
        divided = [[x//P % P for x in row] for row in raw]

        # Modulo 7 the extra line is the first coordinate of this 3-dimensional
        # target.  The first row must vanish for the map to descend without
        # losing rank.  The remaining two rows are the genuine genus-2 target.
        if divided[0] != [0, 0]:
            raise AssertionError(f"v={v}: image meets extra line")
        quotient = divided[1:]
        print(v, extra, quotient, rank2(quotient))


if __name__ == "__main__":
    main()