#!/usr/bin/env python3
"""First-order GL2 classification of the t=0 binary sextic deformation.

Over F_7 write the normalized branch b=1 as

    Y^2 = F_u(X,Z) + 7 G_u(X,Z)  (mod 49),

where

    F_u = 4 X^5 Z + 2 u^2 Z^6,
    G_u = 6 u X^3 Z^3.

For every g in GL_2(F_7) carrying F_u to c F_v, this script tests whether the
transported first-order term differs from G_v by an infinitesimal coordinate
change and y-rescaling.  The tangent space is generated by

    X F_X, Z F_X, X F_Z, Z F_Z, F.

This is the correct first-order obstruction for lifts of binary sextics under
GL_2 and scalar equivalence over the residue field.  The computation is over
F_7; extension of scalars to F_49 is treated separately.
"""

from __future__ import annotations

from itertools import product

P = 7

# Binary degree-6 form represented by coefficients of X^i Z^(6-i), i=0..6.
Vector = tuple[int, ...]


def add(a: Vector, b: Vector) -> Vector:
    return tuple((x + y) % P for x, y in zip(a, b))


def sub(a: Vector, b: Vector) -> Vector:
    return tuple((x - y) % P for x, y in zip(a, b))


def scale(c: int, a: Vector) -> Vector:
    return tuple((c * x) % P for x in a)


def mul_linear_power(a: int, b: int, n: int) -> dict[tuple[int, int], int]:
    """Expansion of (aX+bZ)^n keyed by (X-degree,Z-degree)."""
    from math import comb
    return {(i, n - i): comb(n, i) * pow(a, i, P) * pow(b, n - i, P) % P for i in range(n + 1)}


def transform(form: Vector, g: tuple[int, int, int, int]) -> Vector:
    a, b, c, d = g
    out = [0] * 7
    for i, coefficient in enumerate(form):
        if not coefficient:
            continue
        left = mul_linear_power(a, b, i)
        right = mul_linear_power(c, d, 6 - i)
        for (ix, iz), lv in left.items():
            for (jx, jz), rv in right.items():
                out[ix + jx] = (out[ix + jx] + coefficient * lv * rv) % P
    return tuple(out)


def rank(rows: list[list[int]]) -> int:
    if not rows:
        return 0
    matrix = [row[:] for row in rows]
    r = 0
    cols = len(matrix[0])
    for col in range(cols):
        pivot = next((i for i in range(r, len(matrix)) if matrix[i][col] % P), None)
        if pivot is None:
            continue
        matrix[r], matrix[pivot] = matrix[pivot], matrix[r]
        inv = pow(matrix[r][col] % P, -1, P)
        matrix[r] = [(inv * x) % P for x in matrix[r]]
        for i in range(len(matrix)):
            if i != r and matrix[i][col] % P:
                factor = matrix[i][col] % P
                matrix[i] = [(x - factor * y) % P for x, y in zip(matrix[i], matrix[r])]
        r += 1
        if r == len(matrix):
            break
    return r


def in_span(vector: Vector, generators: list[Vector]) -> bool:
    before = rank([list(g) for g in generators])
    after = rank([list(g) for g in generators] + [list(vector)])
    return before == after


def derivative_x(form: Vector) -> tuple[int, ...]:
    # degree-5 coefficients X^i Z^(5-i), i=0..5
    return tuple(((i + 1) * form[i + 1]) % P for i in range(6))


def derivative_z(form: Vector) -> tuple[int, ...]:
    return tuple(((6 - i) * form[i]) % P for i in range(6))


def multiply_x(deg5: tuple[int, ...]) -> Vector:
    return tuple([0] + list(deg5))


def multiply_z(deg5: tuple[int, ...]) -> Vector:
    return tuple(list(deg5) + [0])


def tangent(form: Vector) -> list[Vector]:
    fx = derivative_x(form)
    fz = derivative_z(form)
    return [multiply_x(fx), multiply_z(fx), multiply_x(fz), multiply_z(fz), form]


def base_form(u: int) -> Vector:
    out = [0] * 7
    out[5] = 4
    out[0] = 2 * u * u
    return tuple(x % P for x in out)


def deformation(u: int) -> Vector:
    out = [0] * 7
    out[3] = 6 * u
    return tuple(x % P for x in out)


def gl2() -> list[tuple[int, int, int, int]]:
    return [(a, b, c, d) for a, b, c, d in product(range(P), repeat=4) if (a * d - b * c) % P]


def scalar_multiple(a: Vector, b: Vector) -> int | None:
    """Return c!=0 with a=c*b, or None."""
    c = None
    for x, y in zip(a, b):
        if y:
            candidate = x * pow(y, -1, P) % P
            if candidate == 0:
                return None
            if c is None:
                c = candidate
            elif c != candidate:
                return None
        elif x:
            return None
    return c


def main() -> None:
    matrices = gl2()
    print("GL2_SIZE", len(matrices))
    edges: dict[int, set[int]] = {u: set() for u in range(1, P)}
    witnesses: dict[tuple[int, int], tuple[int, int, int, int]] = {}

    for u in range(1, P):
        fu = base_form(u)
        gu = deformation(u)
        for v in range(1, P):
            fv = base_form(v)
            gv = deformation(v)
            tv = tangent(fv)
            for g in matrices:
                transported_f = transform(fu, g)
                c = scalar_multiple(transported_f, fv)
                if c is None:
                    continue
                # Restrict to scalar c that is a square in F_7, so it lifts to
                # the y-scaling in an F_7-rational hyperelliptic isomorphism.
                if pow(c, 3, P) != 1:
                    continue
                normalized_g = scale(pow(c, -1, P), transform(gu, g))
                if in_span(sub(normalized_g, gv), tv):
                    edges[u].add(v)
                    witnesses.setdefault((u, v), g)
                    break

    unseen = set(range(1, P))
    components: list[list[int]] = []
    while unseen:
        start = min(unseen)
        stack = [start]
        component: set[int] = set()
        while stack:
            u = stack.pop()
            if u in component:
                continue
            component.add(u)
            stack.extend(edges[u] - component)
            stack.extend(v for v in range(1, P) if u in edges[v] and v not in component)
        unseen -= component
        components.append(sorted(component))

    print("FIRST_ORDER_GL2_ORBITS", len(components))
    for index, component in enumerate(components, 1):
        print(index, component)
    print("EDGES")
    for u in range(1, P):
        print(u, sorted(edges[u]))


if __name__ == "__main__":
    main()